#!/usr/bin/bash

MINIO_ROOT_USER=$MINIO_ROOT_USER \
   MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD \
   /usr/local/bin/minio server $MINIO_VOLUMES \
   --certs-dir $MINIO_CERTS \
   --address $MINIO_DOMAIN:$MINIO_DOMAIN_PORT \
   --console-address :$MINIO_CONSOLE_PORT
